library(tidyverse)
library(stringr)
#Cargar datos
LISTADO_DE_PERSONAL_PROGRAMAS_SOCIALES <- 
        read.csv("~/R Projects/Reporte_Gerencia_BU_2019/Datos/LISTADO_DE_PERSONAL_PROGRAMAS_SOCIALES.csv")
#Limpiar datos
PERSONAL_PS_DDS<- LISTADO_DE_PERSONAL_PROGRAMAS_SOCIALES %>%
        select(c(1:8))
rm(LISTADO_DE_PERSONAL_PROGRAMAS_SOCIALES)
PERSONAL_PS_DDS$Programa <- NA
PERSONAL_PS_DDS$Puesto.Funcional<- str_trim(PERSONAL_PS_DDS$Puesto.Funcional,
         side = "both")
PUESTO_FUNCIONAL <- as.data.frame(unique(PERSONAL_PS_DDS$Puesto.Funcional))
names(PUESTO_FUNCIONAL) <- c("PUESTO")
ALFA_PUESTO_FUNCIONAL <- PUESTO_FUNCIONAL[order(PUESTO_FUNCIONAL$PUESTO),]
ALFA_PUESTO_FUNCIONAL<- as.data.frame(ALFA_PUESTO_FUNCIONAL)
names(ALFA_PUESTO_FUNCIONAL) <- c("PUESTO_1")
ALFA_PUESTO_FUNCIONAL$PUESTO_1[14] <- "BIBLIOTECARIO - BIBLIOTECA CRISTOBAL COLON ZONA 1"
ALFA_PUESTO_FUNCIONAL$PUESTO_1[66] <- "PROFESOR DE COMPUTACION"
ALFA_PUESTO_FUNCIONAL$PUESTO_1[69] <- "SUPERVISOR DE MONITOREO Y EVALUACION"
ALFA_PUESTO_FUNCIONAL$PUESTO_1[13] <- NA
ALFA_PUESTO_FUNCIONAL$PUESTO_1[26] <- NA
ALFA_PUESTO_FUNCIONAL$PUESTO_1[35] <- NA
ALFA_PUESTO_FUNCIONAL$PUESTO_1[62] <- NA
PUESTO_FUNCIONAL<- subset.data.frame(ALFA_PUESTO_FUNCIONAL,
                  !is.na(ALFA_PUESTO_FUNCIONAL$PUESTO_1))
write.csv(PUESTO_FUNCIONAL,
          file = "Puestos funcionales unicos")

CUADRO_INFORMATICA <- PERSONAL_PS_DDS %>%
        select(c(Renglón.Presupuestario, Nombre..Completo, Puesto.Funcional))
write.csv(CUADRO_INFORMATICA,
          file = "Cuadro renglon nombre puesto")

rm(CUADRO_INFORMATICA)
rm(PUESTO_FUNCIONAL)
rm(ALFA_PUESTO_FUNCIONAL)
rm(PERSONAL_PS_DDS)
